# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Manual Compile and Build Installer

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        java-package: 'jdk+fx'
    - name: Build with Ant
      run: |
        pwd
        ant -noinput -buildfile build.xml
        pwd
        ls -l
      shell: bash
    - name: Run the Windows installer batch file
      run: |
          cd installer/windows
          BuildWin.bat
      shell: cmd

    - uses: sillsdev/codesign/.github/workflows/sign.yml@v2
    - name: Sign LingTree installer
#    needs: build-installer
      with:
        artifact: LingTree
      secrets:
        certificate: ${{ secrets.CODESIGN_LSDEVSECTIGOEV }}

#  create-release:
#    name: Create Release
#    needs: sign-installer
#    runs-on: windows-latest
#
#    steps:
#      - uses: actions/download-artifact@v4
#        with:
#          name: LingTree
#
#      - name: Create Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: LingTree-*.exe
#          body: |
#            Release for version ${{ github.ref }}
#          draft: true

#    - uses: actions/upload-artifact@v4
#      with:
#        name: bindir
#        path: bin
#        if-no-files-found: error
#
#  build_installer:
#    name: Build Windows Installer
#    needs: build
#    runs-on: windows-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        java-version: '17'
#        distribution: 'zulu'
#        java-package: 'jdk+fx'
#    - name: Download bin directory
#      uses: actions/download-artifact@v4
#      with:
#       name: bindir
#    - name: Look for bin directory created by ant
#      run: |
#        pwd
#        ls -l
#        find /d/a/lingtree -type d -name bin
#      shell: bash
#    - name: Run the Windows installer batch file
#      run: |
#          cd installer/windows
#          BuildWin.bat
#      shell: cmd
